# Use official Node.js 18 image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Expose app port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]

